---
- name: Import the GPG key for Sublime Text
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add Sublime Text repository
  apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/stable/"
    state: present
    filename: sublime-text

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable"
    state: present
    filename: docker

- name: Add VS Code Asc Key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/packages.microsoft.asc

- name: Add VS Code Repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.asc] https://packages.microsoft.com/repos/code stable main"
    state: present
    filename: vscode

- name: "Install default packages."
  apt:
    name: "{{ defaultsoftware }}"
    state: "present"
    update_cache: yes

- name: Install Zoom
  apt:
    deb: https://zoom.us/client/latest/zoom_amd64.deb
    state: present

- name: "Add automatic updates for VS Code to /etc/apt/apt.conf.d/50unattended-upgrades."
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    line: '        "code stable:stable";'
    insertafter: 'Unattended-Upgrade::Allowed-Origins {'

- name: "Add automatic updates for Docker to /etc/apt/apt.conf.d/50unattended-upgrades."
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    line: '        "Docker:${distro_codename}";'
    insertafter: 'Unattended-Upgrade::Allowed-Origins {'
